server:
  port: 8090

spring:
  datasource: # 数据源的相关配置
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动
    url: jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=PRC
    username: root
    password: root

    # Redis单机实例
  redis:
    database: 0
    host: 192.168.247.135
    port: 6379
    password: Orc123456

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl