server:
  port: 8088

spring:
  datasource: # 数据源的相关配置
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动
    url: jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=PRC
    username: root
    password: root

    # Redis单机实例
  redis:
    database: 0
    host: 192.168.247.135
    port: 6379
    password: Orc123456

    # Redis哨兵模式
#  redis:
#    database: 0
#    password: Orc123456
#    sentinel:
#      master: mymaster
#      nodes: 192.168.247.135:26379,192.168.247.136:26379,192.168.247.137:26379


    # 集群模式(集群模式没有属于哪一个database的概念)
#  redis:
#    password: Orc123456
#    cluster:
#      nodes: 192.168.247.135:6379,192.168.247.136:6379,192.168.247.137:6379,192.168.247.138:6379,192.168.247.139:6379,192.168.247.140:6379
#    timeout: 10000
#    jedis:
#      pool:
#        max-active: 20
#        max-idle: 5
#        min-idle: 0
#        max-wait: -1
#    lettuce:
#      pool:
#        max-active: 10
#        min-idle: 3
#        max-idle: 5

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl